# Project Loan Defaulter

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Machine Learning\Notes\Project-2-The Default Detector Credit Risk Classification\credit_risk_dataset.csv")

In [3]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1

In [4]:
df['Default'].value_counts()

Default
0    862
1    138
Name: count, dtype: int64

In [5]:
df.isnull().sum()

Age                  0
Income              15
Loan_Amount          0
Credit_Score         0
Employment_Years     0
Education_Level      0
Housing_Status       0
Default              0
dtype: int64

In [6]:
df.isnull().sum()/df.shape[0]*100

Age                 0.0
Income              1.5
Loan_Amount         0.0
Credit_Score        0.0
Employment_Years    0.0
Education_Level     0.0
Housing_Status      0.0
Default             0.0
dtype: float64

In [7]:
df['Income']=df['Income'].replace(np.nan, df['Income'].mean())

In [8]:
df.isnull().sum()/df.shape[0]*100

Age                 0.0
Income              0.0
Loan_Amount         0.0
Credit_Score        0.0
Employment_Years    0.0
Education_Level     0.0
Housing_Status      0.0
Default             0.0
dtype: float64

In [9]:
df.select_dtypes(include=['int', 'float']).keys()

Index(['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Default'],
      dtype='object')

In [10]:
df.select_dtypes(include=['object']).keys()

Index(['Education_Level', 'Housing_Status'], dtype='object')

In [11]:
df['Education_Level'].value_counts()

Education_Level
PhD            260
Masters        253
Bachelors      248
High School    239
Name: count, dtype: int64

In [12]:
df['Education_Level'].unique()

array(['Bachelors', 'PhD', 'Masters', 'High School'], dtype=object)

In [13]:
order={'Bachelors':1, 'PhD':3, 'Masters':2, 'High School':0}

In [14]:
df['Education_Level']=df['Education_Level'].map(order)

In [15]:
df['Housing_Status'].value_counts()

Housing_Status
Mortgage    349
Own         330
Rent        321
Name: count, dtype: int64

In [16]:
df['Housing_Status'].unique()

array(['Own', 'Rent', 'Mortgage'], dtype=object)

In [17]:
df=pd.get_dummies(df, columns=['Housing_Status'], drop_first=True, dtype=int)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
X=df.drop(columns=['Default'])

In [21]:
X.head().keys()

Index(['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Education_Level', 'Housing_Status_Own', 'Housing_Status_Rent'],
      dtype='object')

In [22]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [23]:
X_scaled

array([[ 1.30784008, -0.82361042, -1.2885924 , ..., -0.47822822,
         1.42488702, -0.68757112],
       [ 0.5144885 ,  0.94104735,  1.24789457, ...,  1.3128887 ,
         1.42488702, -0.68757112],
       [-0.59620371, -0.57726647, -0.68413362, ...,  0.41733024,
         1.42488702, -0.68757112],
       ...,
       [-0.67553887,  0.56410253, -0.90256268, ...,  0.41733024,
        -0.70181003,  1.45439499],
       [ 1.38717524, -0.43935983, -1.31757008, ...,  1.3128887 ,
         1.42488702, -0.68757112],
       [ 1.38717524,  0.        , -1.57719444, ..., -1.37378668,
        -0.70181003, -0.68757112]])

In [24]:
df1=pd.DataFrame(X_scaled,columns=['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Education_Level', 'Housing_Status_Own', 'Housing_Status_Rent'])

In [25]:
y=df['Default']

In [26]:
df1.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status_Own,Housing_Status_Rent
0,1.307840,-0.823610,-1.288592,1.526363,-0.019095,-0.478228,1.424887,-0.687571
1,0.514489,0.941047,1.247895,-1.678400,-1.183405,1.312889,1.424887,-0.687571
2,-0.596204,-0.577266,-0.684134,-0.965530,-0.834112,0.417330,1.424887,-0.687571
3,1.625181,-0.823610,0.060280,-1.091702,1.261646,-0.478228,-0.701810,1.454395
4,-1.151550,1.822938,0.024332,1.583141,-1.416267,0.417330,1.424887,-0.687571

In [27]:
X_train, X_test, y_train, y_test=train_test_split(df1,y, test_size=0.2, random_state=10)

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr=LogisticRegression(max_iter=1000,class_weight='balanced')

In [30]:
lr.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [31]:
y_pred=lr.predict(X_test)

In [32]:
l=y_train.value_counts()

In [33]:
l[1]/(l[1]+l[0])

np.float64(0.14875)

In [34]:
y_test.value_counts()[0]/(y_test.value_counts()[0]+y_test.value_counts()[1])

np.float64(0.905)

In [35]:
lr.score(X_test, y_test)

0.58

In [36]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [37]:
print(precision_score(y_test, y_pred,))

0.10843373493975904

In [38]:
print(set(y_pred))

{np.int64(0), np.int64(1)}

In [56]:
y_pred

array([1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1])

In [39]:
print(y_test.value_counts())

Default
0    181
1     19
Name: count, dtype: int64

In [40]:
from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[107  74]
 [ 10   9]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.59      0.72       181
           1       0.11      0.47      0.18        19

    accuracy                           0.58       200
   macro avg       0.51      0.53      0.45       200
weighted avg       0.84      0.58      0.67       200

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.59      0.72       181
           1       0.11      0.47      0.18        19

    accuracy                           0.58       200
   macro avg       0.51      0.53      0.45       200
weighted avg       0.84      0.58      0.67       200

In [42]:
from sklearn.preprocessing import PolynomialFeatures

In [43]:
pf=PolynomialFeatures(degree=2)

In [44]:
pf.fit(df1)

PolynomialFeatures()

In [45]:
X_train_poly=pf.transform(df1)

In [46]:
X_train_poly.shape

(1000, 45)

In [47]:
df1.shape

(1000, 8)

In [48]:
pf.fit(X_test)

PolynomialFeatures()

In [49]:
X_test_poly=pf.transform(X_test)

In [50]:
X_test_poly.shape

(200, 45)

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knc=KNeighborsClassifier(n_neighbors=5)

In [54]:
knc.fit(X_train,y_train)

KNeighborsClassifier()

In [55]:
knc.score(X_test, y_test)

0.885

In [57]:
y_pred1=knc.predict(X_test)

In [58]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred1))

Confusion Matrix:
 [[176   5]
 [ 18   1]]

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
dtr=DecisionTreeClassifier()

In [61]:
dtr.fit(X_train, y_train)

DecisionTreeClassifier()

In [62]:
y_pred2=dtr.predict(X_test)

In [63]:
dtr.score(X_test, y_test)

0.765

In [64]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred2))

Confusion Matrix:
 [[147  34]
 [ 13   6]]

In [65]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[107  74]
 [ 10   9]]